package com.svasamm.fhir.integration;

import ca.uhn.fhir.rest.api.MethodOutcome;
import ca.uhn.fhir.rest.param.StringParam;
import ca.uhn.fhir.rest.param.TokenParam;
import com.svasamm.fhir.BaseIntegrationTest;
import com.svasamm.fhir.ehr.provider.PatientResourceProvider;
import org.hl7.fhir.r4.model.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class PatientResourceProviderIntegrationTest extends BaseIntegrationTest {

    @Autowired
    private PatientResourceProvider patientResourceProvider;

    private Patient testPatient;

    @BeforeEach
    void setUp() {
        testPatient = new Patient();
        testPatient.addName().setFamily("IntegrationTest").addGiven("Patient");
        testPatient.setGender(Enumerations.AdministrativeGender.FEMALE);
        testPatient.setBirthDate(java.sql.Date.valueOf("1985-05-15"));
        testPatient.addTelecom()
                .setSystem(ContactPoint.ContactPointSystem.EMAIL)
                .setValue("integration@test.com");
        testPatient.addAddress()
                .addLine("123 Test Street")
                .setCity("Test City")
                .setPostalCode("12345");
    }

    @Test
    @Transactional
    void testCreatePatient_WithAutoGeneratedMRN() {
        // Act
        MethodOutcome createOutcome = patientResourceProvider.create(testPatient);

        // Assert
        assertNotNull(createOutcome);
        assertNotNull(createOutcome.getId());
        assertTrue(createOutcome.getCreated());

        String patientId = createOutcome.getId().getIdPart();

        // Read the created patient
        Patient createdPatient = patientResourceProvider.read(new IdType(patientId));
        
        // Verify basic data
        assertNotNull(createdPatient);
        assertEquals("IntegrationTest", createdPatient.getNameFirstRep().getFamily());
        assertEquals("Patient", createdPatient.getNameFirstRep().getGiven().get(0).getValue());

        // Verify MRN was auto-generated
        assertTrue(createdPatient.getIdentifier().stream()
            .anyMatch(id -> "MR".equals(id.getType().getCodingFirstRep().getCode())),
            "MRN should be auto-generated");

        // Verify hospital-specific enrichment
        assertNotNull(createdPatient.getManagingOrganization());
        assertEquals("Test Hospital", createdPatient.getManagingOrganization().getDisplay());

        // Verify metadata tags
        assertTrue(createdPatient.getMeta().getTag().stream()
            .anyMatch(tag -> "ehr".equals(tag.getCode())));
    }

    @Test
    @Transactional
    void testPatientLifecycle_CreateReadUpdateDelete() {
        // Create
        MethodOutcome createOutcome = patientResourceProvider.create(testPatient);
        String patientId = createOutcome.getId().getIdPart();

        // Read
        Patient readPatient = patientResourceProvider.read(new IdType(patientId));
        assertEquals("IntegrationTest", readPatient.getNameFirstRep().getFamily());

        // Update
        readPatient.getNameFirstRep().setFamily("UpdatedIntegrationTest");
        MethodOutcome updateOutcome = patientResourceProvider.update(new IdType(patientId), readPatient);
        assertNotNull(updateOutcome);

        // Read updated
        Patient updatedPatient = patientResourceProvider.read(new IdType(patientId));
        assertEquals("UpdatedIntegrationTest", updatedPatient.getNameFirstRep().getFamily());
    }

    @Test
    @Transactional
    void testSearchPatients_ByFamily() {
        // Create test patient
        MethodOutcome outcome = patientResourceProvider.create(testPatient);
        assertNotNull(outcome.getId());

        // Search by family name
        List<Patient> searchResults = patientResourceProvider.search(
            new StringParam("IntegrationTest"), null, null, null, null, null
        );

        // Assert
        assertNotNull(searchResults);
        assertTrue(searchResults.size() >= 1);
        
        Patient foundPatient = searchResults.stream()
            .filter(p -> "IntegrationTest".equals(p.getNameFirstRep().getFamily()))
            .findFirst()
            .orElse(null);
        
        assertNotNull(foundPatient);
        assertEquals("Patient", foundPatient.getNameFirstRep().getGiven().get(0).getValue());
    }

    @Test
    @Transactional
    void testSearchPatients_ByMRN() {
        // Create test patient
        MethodOutcome outcome = patientResourceProvider.create(testPatient);
        String patientId = outcome.getId().getIdPart();

        // Read to get the generated MRN
        Patient createdPatient = patientResourceProvider.read(new IdType(patientId));
        String mrnValue = createdPatient.getIdentifier().stream()
            .filter(id -> "MR".equals(id.getType().getCodingFirstRep().getCode()))
            .map(Identifier::getValue)
            .findFirst()
            .orElse(null);

        assertNotNull(mrnValue, "MRN should be generated");

        // Search by MRN
        TokenParam mrnToken = new TokenParam(mrnValue);
        List<Patient> searchResults = patientResourceProvider.search(
            null, null, mrnToken, null, null, null
        );

        // Assert
        assertNotNull(searchResults);
        assertEquals(1, searchResults.size());
        assertEquals(patientId, searchResults.get(0).getIdElement().getIdPart());
    }

    @Test
    @Transactional
    void testPatientSummaryOperation() {
        // Create patient
        MethodOutcome outcome = patientResourceProvider.create(testPatient);
        String patientId = outcome.getId().getIdPart();

        // Call patient summary operation
        Bundle summary = patientResourceProvider.patientSummary(new IdType(patientId));

        // Assert
        assertNotNull(summary);
        assertEquals(Bundle.BundleType.COLLECTION, summary.getType());
        assertNotNull(summary.getId());
        assertNotNull(summary.getTimestamp());
        
        // Should have at least the patient entry
        assertTrue(summary.getEntry().size() >= 1);
        
        // First entry should be the patient
        Bundle.BundleEntryComponent patientEntry = summary.getEntry().get(0);
        assertTrue(patientEntry.getResource() instanceof Patient);
        assertEquals("Patient/" + patientId, patientEntry.getFullUrl());
    }

    @Test
    @Transactional
    void testPatientValidation_MissingName() {
        // Create patient without name
        Patient invalidPatient = new Patient();
        invalidPatient.setGender(Enumerations.AdministrativeGender.MALE);
        invalidPatient.setBirthDate(java.sql.Date.valueOf("1990-01-01"));

        // Should throw validation exception
        assertThrows(IllegalArgumentException.class, () -> {
            patientResourceProvider.create(invalidPatient);
        });
    }

    @Test
    @Transactional
    void testPatientValidation_MissingBirthDate() {
        // Create patient without birth date
        Patient invalidPatient = new Patient();
        invalidPatient.addName().setFamily("Test").addGiven("Patient");

        // Should throw validation exception
        assertThrows(IllegalArgumentException.class, () -> {
            patientResourceProvider.create(invalidPatient);
        });
    }

    @Test
    @Transactional
    void testPatientMerge() {
        // Create source patient
        Patient sourcePatient = new Patient();
        sourcePatient.addName().setFamily("Source").addGiven("Patient");
        sourcePatient.setBirthDate(java.sql.Date.valueOf("1990-01-01"));
        sourcePatient.addIdentifier().setSystem("external").setValue("EXT123");
        sourcePatient.addTelecom().setSystem(ContactPoint.ContactPointSystem.EMAIL).setValue("source@test.com");

        MethodOutcome sourceOutcome = patientResourceProvider.create(sourcePatient);
        String sourceId = sourceOutcome.getId().getIdPart();

        // Create target patient
        Patient targetPatient = new Patient();
        targetPatient.addName().setFamily("Target").addGiven("Patient");
        targetPatient.setBirthDate(java.sql.Date.valueOf("1990-01-01"));

        MethodOutcome targetOutcome = patientResourceProvider.create(targetPatient);
        String targetId = targetOutcome.getId().getIdPart();

        // Merge patients
        MethodOutcome mergeOutcome = patientResourceProvider.mergePatients(
            new IdType("Patient", sourceId),
            new IdType("Patient", targetId)
        );

        // Assert merge was successful
        assertNotNull(mergeOutcome);

        // Read target patient and verify merge
        Patient mergedPatient = patientResourceProvider.read(new IdType(targetId));
        
        // Should have identifiers from both patients
        assertTrue(mergedPatient.getIdentifier().stream()
            .anyMatch(id -> "EXT123".equals(id.getValue())));

        // Should have contact info from source
        assertTrue(mergedPatient.getTelecom().stream()
            .anyMatch(telecom -> "source@test.com".equals(telecom.getValue())));

        // Should have merge history extension
        assertTrue(mergedPatient.getExtension().stream()
            .anyMatch(ext -> ext.getUrl().contains("patient-merge")));

        // Source patient should be deactivated
        Patient sourcePatientAfterMerge = patientResourceProvider.read(new IdType(sourceId));
        assertFalse(sourcePatientAfterMerge.getActive());
    }
}