package com.svasamm.fhir.integration;

import ca.uhn.fhir.rest.api.MethodOutcome;
import ca.uhn.fhir.rest.param.ReferenceParam;
import ca.uhn.fhir.rest.param.TokenParam;
import com.svasamm.fhir.BaseIntegrationTest;
import com.svasamm.fhir.biobank.provider.SpecimenResourceProvider;
import com.svasamm.fhir.ehr.provider.PatientResourceProvider;
import org.hl7.fhir.r4.model.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;

import java.util.Date;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class SpecimenResourceProviderIntegrationTest extends BaseIntegrationTest {

    @Autowired
    private SpecimenResourceProvider specimenResourceProvider;

    @Autowired
    private PatientResourceProvider patientResourceProvider;

    private Patient testPatient;
    private String patientId;
    private Specimen testSpecimen;

    @BeforeEach
    void setUp() {
        // Create test patient first
        testPatient = new Patient();
        testPatient.addName().setFamily("SpecimenTest").addGiven("Patient");
        testPatient.setGender(Enumerations.AdministrativeGender.MALE);
        testPatient.setBirthDate(java.sql.Date.valueOf("1980-01-01"));

        MethodOutcome patientOutcome = patientResourceProvider.create(testPatient);
        patientId = patientOutcome.getId().getIdPart();

        // Create test specimen
        testSpecimen = new Specimen();
        testSpecimen.setSubject(new Reference("Patient/" + patientId));
        testSpecimen.getType().addCoding()
            .setSystem("http://snomed.info/sct")
            .setCode("119297000")
            .setDisplay("Blood specimen");
        testSpecimen.getCollection().setCollected(new DateTimeType(new Date()));
        testSpecimen.getCollection().setQuantity(new Quantity().setValue(10).setUnit("mL"));
        
        // Add container info
        testSpecimen.addContainer()
            .getType().addCoding()
                .setSystem("http://terminology.hl7.org/CodeSystem/v2-0487")
                .setCode("TUBE")
                .setDisplay("Tube");
    }

    @Test
    @Transactional
    void testCreateSpecimen_WithAutoGeneratedBiobankId() {
        // Act
        MethodOutcome createOutcome = specimenResourceProvider.create(testSpecimen);

        // Assert
        assertNotNull(createOutcome);
        assertNotNull(createOutcome.getId());
        assertTrue(createOutcome.getCreated());

        String specimenId = createOutcome.getId().getIdPart();

        // Read the created specimen
        Specimen createdSpecimen = specimenResourceProvider.read(new IdType(specimenId));
        
        // Verify basic data
        assertNotNull(createdSpecimen);
        assertEquals("Patient/" + patientId, createdSpecimen.getSubject().getReference());
        assertEquals("119297000", createdSpecimen.getType().getCodingFirstRep().getCode());

        // Verify biobank ID was auto-generated
        assertTrue(createdSpecimen.getIdentifier().stream()
            .anyMatch(id -> id.getSystem().contains("biobank")),
            "Biobank ID should be auto-generated");

        // Verify collection facility is set
        assertNotNull(createdSpecimen.getCollection().getCollector());
        assertEquals("Test Hospital", createdSpecimen.getCollection().getCollector().getDisplay());

        // Verify biobank metadata tags
        assertTrue(createdSpecimen.getMeta().getTag().stream()
            .anyMatch(tag -> "biobank".equals(tag.getCode())));

        // Verify initial location extension
        assertTrue(createdSpecimen.getExtension().stream()
            .anyMatch(ext -> ext.getUrl().contains("current-location")));
    }

    @Test
    @Transactional
    void testSpecimenLifecycle_CreateReadUpdate() {
        // Create
        MethodOutcome createOutcome = specimenResourceProvider.create(testSpecimen);
        String specimenId = createOutcome.getId().getIdPart();

        // Read
        Specimen readSpecimen = specimenResourceProvider.read(new IdType(specimenId));
        assertEquals("Blood specimen", readSpecimen.getType().getCodingFirstRep().getDisplay());

        // Update
        readSpecimen.setStatus(Specimen.SpecimenStatus.AVAILABLE);
        MethodOutcome updateOutcome = specimenResourceProvider.update(new IdType(specimenId), readSpecimen);
        assertNotNull(updateOutcome);

        // Read updated
        Specimen updatedSpecimen = specimenResourceProvider.read(new IdType(specimenId));
        assertEquals(Specimen.SpecimenStatus.AVAILABLE, updatedSpecimen.getStatus());
    }

    @Test
    @Transactional
    void testSearchSpecimens_BySubject() {
        // Create test specimen
        MethodOutcome outcome = specimenResourceProvider.create(testSpecimen);
        assertNotNull(outcome.getId());

        // Search by patient reference
        ReferenceParam subjectParam = new ReferenceParam("Patient/" + patientId);
        List<Specimen> searchResults = specimenResourceProvider.search(
            subjectParam, null, null, null, null, null
        );

        // Assert
        assertNotNull(searchResults);
        assertTrue(searchResults.size() >= 1);
        
        Specimen foundSpecimen = searchResults.stream()
            .filter(s -> ("Patient/" + patientId).equals(s.getSubject().getReference()))
            .findFirst()
            .orElse(null);
        
        assertNotNull(foundSpecimen);
        assertEquals("119297000", foundSpecimen.getType().getCodingFirstRep().getCode());
    }

    @Test
    @Transactional
    void testSearchSpecimens_ByType() {
        // Create test specimen
        MethodOutcome outcome = specimenResourceProvider.create(testSpecimen);
        assertNotNull(outcome.getId());

        // Search by specimen type
        TokenParam typeParam = new TokenParam("http://snomed.info/sct", "119297000");
        List<Specimen> searchResults = specimenResourceProvider.search(
            null, null, typeParam, null, null, null
        );

        // Assert
        assertNotNull(searchResults);
        assertTrue(searchResults.size() >= 1);
        
        Specimen foundSpecimen = searchResults.stream()
            .filter(s -> s.getType().getCoding().stream()
                .anyMatch(coding -> "119297000".equals(coding.getCode())))
            .findFirst()
            .orElse(null);
        
        assertNotNull(foundSpecimen);
    }

    @Test
    @Transactional
    void testChainOfCustodyOperation() {
        // Create specimen
        MethodOutcome outcome = specimenResourceProvider.create(testSpecimen);
        String specimenId = outcome.getId().getIdPart();

        // Call chain of custody operation
        Bundle custody = specimenResourceProvider.chainOfCustody(new IdType(specimenId));

        // Assert
        assertNotNull(custody);
        assertEquals(Bundle.BundleType.COLLECTION, custody.getType());
        assertNotNull(custody.getId());
        assertNotNull(custody.getTimestamp());
        
        // Should have at least the specimen entry
        assertTrue(custody.getEntry().size() >= 1);
        
        // First entry should be the specimen
        Bundle.BundleEntryComponent specimenEntry = custody.getEntry().get(0);
        assertTrue(specimenEntry.getResource() instanceof Specimen);
        assertEquals("Specimen/" + specimenId, specimenEntry.getFullUrl());
    }

    @Test
    @Transactional
    void testSpecimenLocationOperations() {
        // Create specimen
        MethodOutcome outcome = specimenResourceProvider.create(testSpecimen);
        String specimenId = outcome.getId().getIdPart();

        // Get current location
        Location currentLocation = specimenResourceProvider.specimenLocation(new IdType(specimenId));
        assertNotNull(currentLocation);
        assertEquals("Receiving Area", currentLocation.getName());

        // Update location
        Reference newLocation = new Reference().setDisplay("Freezer A1");
        MethodOutcome updateOutcome = specimenResourceProvider.updateLocation(
            new IdType(specimenId), newLocation, "Moved to long-term storage"
        );
        assertNotNull(updateOutcome);

        // Verify location was updated
        Specimen updatedSpecimen = specimenResourceProvider.read(new IdType(specimenId));
        Extension locationExt = updatedSpecimen.getExtensionByUrl(
            "http://hospital.local/fhir/StructureDefinition/current-location"
        );
        assertNotNull(locationExt);
    }

    @Test
    @Transactional
    void testSpecimenValidation_MissingSubject() {
        // Create specimen without subject
        Specimen invalidSpecimen = new Specimen();
        invalidSpecimen.getType().addCoding()
            .setSystem("http://snomed.info/sct")
            .setCode("119297000");

        // Should throw validation exception
        assertThrows(IllegalArgumentException.class, () -> {
            specimenResourceProvider.create(invalidSpecimen);
        });
    }

    @Test
    @Transactional
    void testSpecimenValidation_MissingType() {
        // Create specimen without type
        Specimen invalidSpecimen = new Specimen();
        invalidSpecimen.setSubject(new Reference("Patient/" + patientId));

        // Should throw validation exception
        assertThrows(IllegalArgumentException.class, () -> {
            specimenResourceProvider.create(invalidSpecimen);
        });
    }

    @Test
    @Transactional
    void testSpecimenValidation_MissingCollectionInfo() {
        // Create specimen without collection info
        Specimen invalidSpecimen = new Specimen();
        invalidSpecimen.setSubject(new Reference("Patient/" + patientId));
        invalidSpecimen.getType().addCoding()
            .setSystem("http://snomed.info/sct")
            .setCode("119297000");
        // No collection info

        // Should throw validation exception
        assertThrows(IllegalArgumentException.class, () -> {
            specimenResourceProvider.create(invalidSpecimen);
        });
    }
}